### ISSUE TITLE
Snitch cluster using deprecated l1_subsystem perf counters

### ISSUE THREAD

**Issue by sermazz** [gvsoc/gvsoc-pulp#10] opened 2024-06-27 08:12 UTC
The Snitch cluster model, in particular the l1_subsystem, is using deprecated perf counters which are not anymore supported by the generic router (which was updated here: https://github.com/gvsoc/gvsoc-core/commit/df7f6eca34c29625ae136cc3da6dd981892d76ee#diff-ef2e7863059c5950dd7fd6fa69a10615343cb41d2fce3b54863719c4a816fe1eL52-R120).
https://github.com/gvsoc/gvsoc-pulp/blob/3ca2016d056dda72317e27c4319fc6174b5f8c4d/pulp/snitch/l1_subsystem.py#L121-L140
I think it should be changed in a similar way to this https://github.com/gvsoc/gvsoc-pulp/commit/3ca2016d056dda72317e27c4319fc6174b5f8c4d

**Comment by sermazz** [comment] 2024-06-27 15:28
Solved in https://github.com/gvsoc/gvsoc-pulp/pull/11

**Comment by haugoug** [comment] 2024-07-12 09:22
Sorry I was not properly watching the repository and did not see your issue.
I think the problem is fixed now, can you try and let me know ?

**Closed** 2024-07-19 06:01 UTC
